"""add audit logs table and middleware wiring

Revision ID: 92093110c13f
Revises: 677a6b8f90ea
Create Date: 2025-08-22 11:42:59.582572
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92093110c13f'
down_revision = '677a6b8f90ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
